### ISSUE TITLE
Test Opening e57 file and Read informations

### ISSUE THREAD

**Issue by pierrenavarra** [openE57/openE57#25]
Hi madduci
I try to read a simple e57 file 
For exemple, I'd like to get : 

- number of scans ? (cose multiple scans can be into a E57)
- For each scan : the number of points and the position of the scan (X,Y,Z)
- And maybe the top will be to get the 360 image...

Like I've got when opening it into Scene 

![image](https://user-images.githubusercontent.com/54843266/154228260-4aa094ee-5900-4c23-9582-09b8180eb411.png)

Is it possible?

It seems to be on fata3D/index0/pose/translation..

![image](https://user-images.githubusercontent.com/54843266/154232510-7f6193c5-8817-4a88-9f65-2000e494b5cb.png)

I had a look on samples but no way to find a code...
Many thx...

**Comment by madduci** [comment]
Hi,

Thanks for the questions. You can refer still to the official libE57
documentation (http://libe57.org/documentation.html), since the APIs aren't
changed, but only the namespace `e57::` was added on this fork until now.

The updated documentation for this repository is work in progress and I
hope to publish it soon.

**Comment by madduci** [comment]
Closing the issue, it will be resolved with #13
